### ISSUE TITLE
RETURNS TABLE support

### ISSUE THREAD

**Issue by emrul** [plv8/plv8js#314]
I'm wondering if there's any plan to support functions that return tables like here: http://www.postgresqltutorial.com/plpgsql-function-returns-a-table/

It would be really handy for cases where I want to generate an SQL query in plv8 and return the results.

**Comment by JerrySievert** [comment]
you mean like:

```
CREATE FUNCTION test_data ( )
RETURNS TABLE (foo VARCHAR, bar VARCHAR)
AS $$
return [ { "bar", "baz" }];
$$ LANGUAGE plv8;
```

```
[local] jerry@test=# select * from test_data();
┌─────┬─────┐
│ foo │ bar │
├─────┼─────┤
│ bar │ baz │
└─────┴─────┘
(1 row)
```

?

**Comment by JerrySievert** [comment]
that's essentially a short-cut for returning a `set` - see https://plv8.github.io/#set-returning-function-calls

**Comment by emrul** [comment]
I was thinking (something) like:
```
CREATE FUNCTION test_data ( )
RETURNS TABLE (foo VARCHAR, bar VARCHAR)
AS $$
return plv8.query("SELECT foo, bar FROM a_table");
$$ LANGUAGE plv8;
```

The difference being for cases where the result set is rather large (20k rows) and I have a lot of concurrent requests.  With set returning functions plv8 has to load the results of the query into its tuplestore which I was considering to avoid.

**Comment by JerrySievert** [comment]
that's essentially what `plpgsql` ~is~ might be doing, it's using `SPI` under the hood:

https://doxygen.postgresql.org/datum_8c_source.html#l00190

in some instances, it's doing a copy, in others it's just copying the pointer, depending on the lifespan.  since plv8 is an interpreted language that includes another run-time, it needs to be dealt with in order to return - the only way to get around that would to have a new type for this specifically that would handle that single case outside of javascript, where it may make a copy or may not.  in the case where it doesn't copy, it would probably just be better to write it in plpgsql.

otherwise, your example works:

```
CREATE FUNCTION test_data ( )
RETURNS TABLE (foo VARCHAR, bar VARCHAR)
AS $$
return = plv8.execute("SELECT 'foo' AS foo, 'bar' AS bar");
$$ LANGUAGE plv8;
```

here's an example:

```
[local] jerry@test=# \d test_data
                           Table "public.test_data"
┌───────────────────┬────────────────────────┬───────────┬──────────┬─────────┐
│      Column       │          Type          │ Collation │ Nullable │ Default │
├───────────────────┼────────────────────────┼───────────┼──────────┼─────────┤
│ facility_alias_id │ integer                │           │          │         │
│ group_type_id     │ integer                │           │          │         │
│ product_id        │ integer                │           │          │         │
│ catalog_stripped  │ character varying(300) │           │          │         │
│ po_date_month     │ date                   │           │          │         │
│ histogram         │ histogram              │           │          │         │
│ total_spend       │ numeric                │           │          │         │
│ min_price         │ numeric                │           │          │         │
│ max_price         │ numeric                │           │          │         │
│ min_po_date       │ date                   │           │          │         │
│ max_po_date       │ date                   │           │          │         │
│ most_recent_price │ numeric                │           │          │         │
│ total_eaches      │ numeric                │           │          │         │
└───────────────────┴────────────────────────┴───────────┴──────────┴─────────┘

[local] jerry@test=# SELECT COUNT(*) FROM test_data;
┌───────┐
│ count │
├───────┤
│ 70228 │
└───────┘
(1 row)
```

```
CREATE FUNCTION bigger_test ()
RETURNS TABLE (foo VARCHAR, bar VARCHAR)
AS $$
return plv8.execute("SELECT total_spend::VARCHAR AS foo, min_price::VARCHAR as BAR FROM test_data");
$$ LANGUAGE plv8;
```

```
[local] jerry@test=# select bigger_test();
┌──────────────────────────────┐
│         bigger_test          │
├──────────────────────────────┤
│ (7452.90000000,2484.3000)    │
│ (29811.60000000,2484.3000)   │
│ (24843.00000000,2484.3000)   │
[...]
│ (71.92000000,71.9200)        │
└──────────────────────────────┘
(70228 rows)

Time: 425.471 ms
```

slower than the original query, which returned in 60ms, as opposed to 425ms, but not too bad considering.

I'd consider a PR for it, but without a compelling argument likely won't write it myself, since it does work as-is and there are alternatives

note that

```
CREATE FUNCTION bigger_plpgsql()
RETURNS TABLE (foo VARCHAR, bar VARCHAR)
AS $$
BEGIN
  RETURN QUERY SELECT total_spend::VARCHAR AS foo, min_price::VARCHAR AS BAR FROM test_data;
END;
$$ LANGUAGE plpgsql;
```

returns in about 100ms for me, which is slower than the original query by ~80% which is about what I'd expect given the overhead of v8.

if you're using `return_next()`, the memory overhead should be comparable to plpgsql if the tuple ends up needing to be copied, but the queries are returning too quickly for me to get an accurate memory read on either side, plus the copy vs pointer argument would likely depend on the query being executed - mine is obviously manufactured, since it's doing a `cast`.
