### ISSUE TITLE
First connection function call really slow

### ISSUE THREAD

**Issue by ooldham** [plv8/plv8js#315]
Hi, we are using an AWS RDS postgresql service, and are experiencing LONG execution times of plv8 function calls - BUT only on the FIRST call. A subsequent call, using the same connection does not have a long execution time...
(Note: All plv8 versions mentioned here are the 'trusted' flavors)

On RDS system1: we have postgres v9.6.6, plv8 1.4.4
- first connection call round trip inc connection/login: ~ 0.40 seconds
- first connection call SQL only: 64.518 ms

On RDS system2: we have postgres v9.6.11, plv8 2.1.2
- first connection call round trip inc connection/login: ~ 2 - 3 seconds
- first connection call SQL only: 1825.935 ms

On EC2 system3: we have postgres v10.1, plv8 1.4.10
- first connection call round trip inc connection/login: ~ 0.40 seconds
- first connection call SQL only: 55.846 ms

I am not sure at which version of plv8 the execution time jump occurs.
A conversation with an AWS agent revealed that a setup with RDS postgres 9.6.6 plv8 1.5.3 execution
time was similar to 1.4.X times (ie faster).

Can we expect a fix for this in the near future?
Thanks

**Comment by JerrySievert** [comment]
do you have an example that you can share, or any other information?

essentially, you've said:

> we have a black box running on a black box and things are slower in one black box than another black box.  when will that be fixed?

**Comment by ooldham** [comment]
Yes, sorry, I forgot to include the 2 functions I used for testing...

Here is my plv8 function -------
CREATE OR REPLACE FUNCTION f_junk1()
 RETURNS int AS $function$

return 1;
$function$
LANGUAGE plv8
;

Here is my plpgsql function -------
CREATE OR REPLACE FUNCTION f_junk2 ()
RETURNS int AS $function$

BEGIN
return 1;
END
$function$
language 'plpgsql';
;

Prerequisites:
o Have 2 instances of a server or RDS with postgresql installed on it
  with your choice: 9.6.6, 9.6.11, 10.1.N - does not appear to make a difference
o Have one instance with plv8 v 1.4.10 or v 1.5.3
o Have the other instance with plv8 v 2.1.2
o install the functions: f_junk1, f_junk2 on both instances
o Disconnect from both instances

Execution:
o connect to instance1 (plv8 v1.4.10 or 1.5.3) via psql
o turn on timing
o psql> \timing
o psql> select f_junk1();  -- and note the ms time (plv8 function)
o psql> select f_junk2(); -- and not the ms time (plpgsql)
o psql> select f_junk1(); -- 2nd run, notice the time is not much different

o connect to instance2 (plv8 v2.1.2) via psql
o psql> \timing
o psql> select f_junk1();
o psql> select f_junk2();
o psql> select f_junk1(); -- 2nd run, NOTICE how much faster this one is...

I also have a perl function that I used, but we try not to use perl...
perl exec times are similar to plpgsql, and are 'faster' on the first call post connect.

I am happy to answer any other questions...

**Comment by JerrySievert** [comment]
There’s a lot here to respond to, so i’ll try cover as much as i can in one go, but will likely have to switch to a computer to respond fully:

## plv8 vs plpgsql

`pl/pgsql` has a very simple DSL, and has an extremely lightweight startup time compared to a full-featured language with classes, memory management, JIT, and garbage collection.  Comparing them at all for startup time is not applicable.  A quick analogy would be like comparing the acceleration time of a motorcycle and a bus.  Sure, the motorcycle will accelerate a lot more quickly, but it can’t carry 100 passengers from point a to point b.

That said, on first connection, the example you provided executes in a couple of ms on first start with continued calls under 1ms for me.  Obviously, this isn’t your example of a couple of seconds, so that still leaves us with a couple of complete black boxes:

* RDS
* your function

there are several ways to mitigate startup times, regardless of your environment, which you should be using with Postgres, even if you’re not using plv8, with the most common being connection pooling.  It sounds like you’re not using connection pooling, which should be your first stop regardless.


As far as differences between plv8 1.4 and 2.1, these strictly have to do with v8 versions/features and interfacing with v8 itself, which has had many major changes under the hood ranging from major changes in language features to spectre/meltdown mitigation, changes how it deals with memory, and a ton of other changes under its hood.


Regardless, without more information, i can only give you generic pointers.

**Comment by JerrySievert** [comment]
Btw, i will note that every version of plv8 is “trusted” - there is no untrusted version of plv8 at this time.  This makes a bit of difference for startup time, in that v8’s startup mitigation is to use *snapshots*.

**Comment by JerrySievert** [comment]
closing, as there is no further information, and examples given were very few ms.
