### ISSUE TITLE
find_function bypasses all the security controls for functions

### ISSUE THREAD

**Issue by pkit** [plv8/plv8js#326]
```
admin=# create function a() returns text as $$ return 'test' $$ language plv8;
CREATE FUNCTION
admin=# revoke execute on function a() from public;
REVOKE
admin=# set role test;
SET
admin=> select a();
ERROR:  permission denied for function a
admin=> do $$ const f = plv8.find_function('a'); plv8.elog(INFO, f()) $$ language plv8;
INFO:  test
DO
```
After analyzing the code I don't see how it can be mitigated (grants are at least static, but check constraints on domain types anyone?).
Probably just need to mention it in the documentation.

**Comment by JerrySievert** [comment]
thanks for the report - this goes back to way before my time, yikes.

hm. there might be the possibility of mitigation via the same method I used for `plv8.start_proc`: https://github.com/plv8/plv8/blob/r3.0alpha/plv8.cc#L1565 since the `Oid` is known at that point.

I've been deep in the bowels of plv8 this weekend, working on better `JSONB` support, so I'll see if I can switch gears after that and either get it fixed with some back-ports or at the very least do as you suggested and get it mentioned in the documentation.

it makes me wish that pg had role scoped permissions check on function calls, since extensions can easily bypass all permissions checks.

**Comment by pkit** [comment]
Hmm, I have seen this weird juggling in start_proc before. Probably need to
take a closer look at it.
But my current problem is much bigger than a simple permission check. I
need runtime argument checks.
Therefore I have disabled `find_function` for now.

**Comment by JerrySievert** [comment]
yeah, the argument checks make it a bit harder:

```
CREATE FUNCTION foo(VARCHAR) ...
```

```
CREATE FUNCTION foo() ...
```

I don't know how often `find_function` is used, unfortunately - I'm tempted to just disable it completely as a breaking change in 3.0 - the cost is pretty close to `SELECT function()` as-is, minus the parsing, and plus the lack of language focus, but given that making assignments to the `plv8` object is a better solution overall, it might make sense to get rid of it.

do you have a specific case where `find_function` is useful, that might persuade me?

**Comment by pkit** [comment]
Nope. I have disabled it and just use `select func()` everywhere.

**Comment by JerrySievert** [comment]
yeah, that's the functionality I use.  I'll disable it for 3.0 forward, regardless, and see if anyone balks.

**Comment by pkit** [comment]
I have also disabled `elog` it looks too tempting. After all people can
always `pg_notify` and at least see it in the client.

**Comment by JerrySievert** [comment]
`elog` I'm not too concerned about, since the same functionality is available via `pgpsql` without any rights.

**Comment by JerrySievert** [comment]
turned out to be a fairly straightforward change.

I'm going to take some time to refactor the find_function functionality, but I have a clean fix in place.

this will take affect in 3.0alpha and later.

still wondering why you're disabling `elog`, since this works the same:

```
=# DO $$ BEGIN RAISE NOTICE 'hey! I''m a log!'; END $$ LANGUAGE plpgsql;
```

**Comment by JerrySievert** [comment]
back-ported to 2.3.11
