### ISSUE TITLE
undefined symbol: _ZNSt3__119__shared_weak_countD2Ev

### ISSUE THREAD

**Issue by zhangwenjiepger** [plv8/plv8js#339]
What versions of related things I used?
CentOS Linux release 7.6.1810
PostgreSQL 9.2.24：yum install postgresql 
plv8 2.3.11 release: get from the repo
gcc  (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

What steps will reproduce the problem?
1.  cd plv8-2.3.11
2. make
3. make install
4. su postgres
5. /usr/bin/psql postgres -c "create extension plv8;"
It return that:
ERROR:  could not load library "/usr/lib64/pgsql/plv8-2.3.11.so": /usr/lib64/pgsql/plv8-2.3.11.so: undefined symbol: _ZNSt3__119__shared_weak_countD2Ev

I don't know why. Anyone can help me ?

**Comment by JerrySievert** [comment]
gcc `4.8.5` is pretty old at this point, which wouldn't be so bad except they hadn't implemented `c++11` at that point - you're seeing some missing c++ functionality from linking.

there are a couple of ways you can proceed:

there's an old note in one of the Makefiles: https://github.com/plv8/plv8/blob/r3.0alpha/Makefile.shared#L66-L67

```
# for older g++ (e.g. 4.6.x), which do not support c++11
#OPTFLAGS = -O2 -std=gnu++0x -fno-rtti
```

you can try uncommenting the `OPTFLAGS` line, running `make clean`, then `make` and `make install` again.

you can also look at replacing or augmenting the compiler - clang++ from 2015 had great `c++11` support, you might consider installing it and after running `make clean`, run `make CUSTOM_CC=clang++`

otherwise, you'll need to look at using the `2.1`versions, `2.1.2` being most recent when a `bytea` fix was back ported from the `2.3` branch.  the differences between dot release versions is the v8 version that is supported:  the `2.1` branch uses v8 `5.8.301`.

**Comment by zhangwenjiepger** [comment]
Thank you for your prompt reply.
I uncommenting the OPTFLAGS line, running make clean, then make and make install again. But it return the same error.
Unfortunately, replacing g++ to clang++ will cost a lot time for me. 
I choose to use the 2.1 versions. It works for me.

**Comment by nonara** [comment]
This same problem happens to me on CentOS 7. I've used gcc 4, 6, 7, & 8 to no avail.

No matter what version of gcc I use, it always says "cannot find -lc++"
When I change it to -llibc++, it compiles but has the same error:

undefined symbol: _ZNSt3__119__shared_weak_countD2Ev

with clang 3.4.2 I get 
clang: error: unknown argument: '-fexcess-precision=standard'
clang: error: unknown argument: '-fstack-protector-strong'

**Comment by nonara** [comment]
Got it to compile with clang 5.0 (I removed -lc++ from Makefile)

Amazingly, it's still throwing the same _ZNSt3__119__shared_weak_countD2Ev error!

**Comment by JerrySievert** [comment]
yes, because v8 needs `libc++`.

did you try `dnf repoquery --whatprovides libc++* --arch x86_64` and install the required libc++ library?

**Comment by nonara** [comment]
libc++ was installed. Seems that libcxx would install `libc++.so.1.0` to /usr/lib64, but the compiler could not recognize it.

Creating a symlink as `libc++.so` or, more preferably, installing libcxx-devel (which creates the symlink) seems to have done the trick.

Thanks for the response and the great work!

For reference - my fix on CentOS Linux release 7.2.1511
1. sudo yum install -y libcxx libcxx-devel
2. sudo yum install -y llvm7.0 llvm7.0-devel llvm7.0-libs
3. Edit Makefile.shared and change compiler to clang
4. make

You may also be able to get it to work using g++ by following:
1. sudo yum install -y libcxx libcxx-devel
2. sudo yum install -y devtoolset-8
3. scl enable devtoolset-8 bash
4. make

Repositories used:
* EPEL - [How-To install EPEL](https://www.tecmint.com/install-epel-repository-on-centos/)
* SCLo - [How-To install SCLo](https://github.com/sclorg/centos-release-scl)

**Comment by JerrySievert** [comment]
I was about to ask about the `-devel` package, just wasn't sure what the package name is for fedora/redhat (it's `libc++-devel` for debian/ubuntu).

**Comment by xsacha** [comment]
Just came across this on Amazon Linux 2.
You need to enable EPEL repository first
$ `sudo amazon-linux-extra install epel`
Then you need to install libcxx and libcxx-devel (Unsure if devel is necessary but the person above did this)
$ `sudo yum install libcxx libcxx-devel`
Now it will make fine. No need to change compiler. It links in libc++ which satisfies the v8 dependency.
