### ISSUE TITLE
supporting es6 import

### ISSUE THREAD

**Issue by erichanson** [plv8/plv8js#341]
How feasible would it be to support es6 [import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) from within plv8?  I appreciate plv8's stance of being rather agnostic about how modules are loaded, since the whole module scene has been fairly volatile over the years, but it seems like the world is moving towards es6 modules?  Do folks concur with this analysis?  Since plv8 can't read from the filesystem, would it even be possible to make import work but instead load from the database?  Generally speaking, are there any best practices that have emerged around module loading from plv8?

The relevant projects I've found so far are:

- [plv8-modules](https://github.com/JerrySievert/plv8-modules)
- [es6-to-plv8](https://github.com/CSTARS/es6-to-plv8)
- [plv8x](https://github.com/clkao/plv8x)
- [node-plv8](https://github.com/langateam/node-plv8)

**Comment by JerrySievert** [comment]
I've spent a few minutes looking at the feasibility, and here's where I'm at:

```
V8 version 7.0.302
d8> import "foo"
(d8):1: SyntaxError: Unexpected string
import "foo"
       ^^^^^
```

if the `import` keyword can be implemented in plv8, these are the issues that would need to be solved:

* permissions - since `plv8` can be executed by any role that has permission to the database, any module storage system would need to either honor role based Postgres permissions or have the ability to disable `import` for selective environments.  `plv8` currently uses role permissions checks when using its internal `find_function` method.
* agnostic system of management - adding requirements for a specific run-time environment to use modules is cumbersome, and this would need to be figured out
* version management - see the mess that is npm version management for an example

I can look further into supporting the `import` keyword, and am happy to leave this issue open while some of the other parts are discussed and either solved or found to be blockers.

I'm definitely not opposed to it, but it will have to be well thought out and implemented, and now is the correct time to have that discussion.

**Comment by pkit** [comment]
permissions are easy, if you use the database itself to store these modules, i.e. tables
actually it's not that hard to implement some sort of a centralized module repo and then `npm.install()` from it

**Comment by erichanson** [comment]
Pardon the basic question, but does plv8 issue database queries using the same role that called the function?  Does it honor the SECURITY DEFINER directive?  Having import just stay within the Postgres permissions system seems ideal to me.  Folks making use of row-level security would definitely want that as well.

Versioning -- definitely!  But... since import just references a `import foo from '/some/file.js'`, it's not clear where versioning fits in here other than just including it in filename, unless we wanted to extend the syntax somehow.

One idea would be to allow plv8 to be configured with a `module_table` directive, the specifies where modules are to be loaded from.  This table could be required to have a `name` column, which is what would be used as the "filename" in the lookup.

**Comment by JerrySievert** [comment]
queries, yes, but plv8 runs as an extension and thus has a lot higher privileges itself, and checks permissions when using internal pg functionality.

see https://github.com/plv8/plv8/blob/r3.0alpha/plv8_func.cc#L1091 for an example.

**Comment by JerrySievert** [comment]
@pkit yeah, that's what plv8_modules does, completely at the db level using `plv8.execute`, but it looks like implementing `import` would require code at the c++ level if I'm reading it correctly.

**Comment by pkit** [comment]
But isn't it still just an SPI interface that will check all the permissions at the beginning of query execution?

**Comment by erichanson** [comment]
Thinking about where to import from, how about framing it as:  We want the ability to import Javascript code from any arbitrary SQL statement that returns text, something very roughly like:

```javascript
// import from a database table
import foo from plv8.execute('select content from some.table where id=12345')
```

That way you could even call functions, potentially even from untrusted languages if the user wanted to do that.  These functions could import Javascript code from the filesystem or go grab code from a CDN or who knows what -- whatever the current database role can already do, as configured by the developer:

```javascript
// import from a remote CDN
import foo from plv8.execute("select response from http_client.get('http://example.com/some/file.js')")

// import from a file
import foo from plv8.execute("select pg_read_file('/some/file.js')");
```

Not that these last two examples are necessarily *good* ideas, but point being, if it allows the user to specify arbitrary SQL somehow, they can basically pull from the database however they please, which keeps things very flexible, and plv8 doesn't have to make arbitrary/opinionated decisions about how things are done.

I don't think the above syntax is quite right.  Ideally `import` would support inline values somehow.

**Comment by JerrySievert** [comment]
`plv8.execute` uses the SPI functions, but `plv8.find_function` uses `regprocin` and `regprocedurein`.

**Comment by JerrySievert** [comment]
hm. interesting idea.  let me see what I can throw together in the next few days - but have something a little higher priority brewing at this moment.

**Comment by erichanson** [comment]
A different syntax idea could just be to have the filename parameter of `import` instead be an arbitrary SQL string, like:

```javascript
import {foo, bar} from "select code from whatever.table where name='mylib'"
```

**Comment by micburks** [comment]
I'm interested in how closely plv8 can follow node's progress on this. Node currently has a [runtime flag](https://nodejs.org/api/esm.html#esm_enabling) that enables es module syntax. This will *hopefully* soon be supported without an experimental flag. The es module spec says that static imports are top-level and have an (*obviously*) static target, whereas the `import()` function syntax can accept a [dynamic value](http://2ality.com/2017/01/import-operator.html). Following this standard would enable a lot of what is being talked about here, possibly with the addition of a [custom loader](https://nodejs.org/dist/latest-v12.x/docs/api/cli.html#cli_loader_file) to load js modules from a table.

Admittedly, I don't know much about how this all works, but syntax in plv8 should just use whatever version of node it was compiled against. Maybe the default behavior would be that plv8 uses a `node_modules` directory specified in an environment variable (`PLV8_MODULES_DIR=/var/node_modules`).

**Comment by erichanson** [comment]
@micburks Well, to be precise, and correct me if I'm wrong, but my understanding is that plv8 isn't compiled against a particular version of node, rather they're both compiled against a particular version of v8.  I learned a lot from Ryan Dahl's "10 things I Regret About Node" ([notes](https://medium.com/@imior/10-things-i-regret-about-node-js-ryan-dahl-2ba71ff6b4dc), [video](https://www.youtube.com/watch?v=M3BM9TB-8yA)) where he basically trashes node's packaging system as a largely unnecessary abstraction that is not "how the web works".

I see great value in finding some way to play nice with the universe of cool stuff available on npm, but also wouldn't want to see plv8 make decisions that tie it to node's mistakes.  There is also a lot of stuff in npm that will never make sense in the context of plv8.  It seems like we just want the Javascript modules, and the rest of the stuff in there is really a different animal.

But I don't know that much about how node works so I could be wrong.  Maybe node integration could be built on top of our database-aware `import` statement primitive, while still allowing people to do stuff that isn't node-specific?  Or maybe it's a different goal all together?

**Comment by JerrySievert** [comment]
plv8 isn't compiled against any version of node.  it, like node, is a consumer of v8, and different versions of plv8 are tied to different versions of v8, just like different versions of node are tied to different versions of v8.  that's pretty much where the similarity ends.

plv8 is also a *trusted* module and explicitly does not have access to the filesystem, so therefor there is no `node_modules` directory.

**Comment by micburks** [comment]
Ah I see. Indeed I recalled incorrectly. I'm not sure this conversation actually had much to do with importing external code, so forget I mentioned `node_modules`.

Regardless, if `import` was to be supported, it would be the least confusing if it followed the static/dynamic patterns I mentioned above.

```js
import("select code from whatever.table where name='mylib'").then(module => {
  const MyLibrary = module.default;
});
// or 
import MyLibrary from 'whatever.table??';
// would be intuitive approaches
```

**Comment by pkit** [comment]
> ```js
> // import from a database table
> import foo from plv8.execute('select content from some.table where id=12345')
> ```

That's fun and all but it cannot resolve underlying imports
Unless you webpack/rollup/browserify everything into one file
btw at least browserify runs perfectly ok within plv8 (hint, hint)
and if you use some packager anyway it can be done with regular `require` right now

> ```js
> // import from a remote CDN
> import foo from plv8.execute("select response from http_client.get('http://example.com/some/file.js')")
> 
> // import from a file
> import foo from plv8.execute("select pg_read_file('/some/file.js')");
> ```

while reading files is a bad idea, loading things from network - is pretty ok, you can control and tighten up places that the server has access to.

**Comment by erichanson** [comment]
Not sure I follow, what are underlying imports?  Anything doing any importing in plv8 would need to use import statements that make sense in a database I presume.

I could imagine scenarios where loading from file could make sense -- like if you're building a PostgreSQL administration tool, and connecting as a superuser anyway.  Or through a SECURITY DEFINER function that limits where in the filesystem it is allowed to look.

**Comment by erichanson** [comment]
I'm running into needing this again, this time trying to do some headless chrome / puppeteer stuff from plv8.  Talk about a perfect screen-scraping and automation foundation, plv8 + puppeteer could be really incredible.

Anyway thought I'd bump this issue.  Did you get anywhere with taking a crack at implementing `import`?

As far as design, this is a central enough issue that, what do you think about maybe asking the postgresql-hackers list for design ideas -- they seem to be really good at debating different approaches and coming up with something sensible.

**Comment by JerrySievert** [comment]
I haven't had the time to spend more time than the highest level look at implementing `import`.

you should note though that plv8 is a trusted language, so using puppeteer to control a headless browser just plain isn't going to work.  I could see perhaps using something like cheerio and Paul's [pgsql-http](https://github.com/pramsey/pgsql-http), but still wouldn't recommend doing that inside of Postgres, regardless of the language used.

as for pg-hackers, there's a core group there that despises plv8 (from long before I've been around plv8), so, um, good luck with that :)

**Comment by erichanson** [comment]
Yeah true on the trusted lang.  A plv8u would be fun. :-)

That's weird.  What do they hate about plv8?

**Comment by JerrySievert** [comment]
> Yeah true on the trusted lang. A plv8u would be fun. :-)

I've made a couple of false starts on plv8u, but backed off because of the amount of work it would be for what would ultimately end up being a hard fork and difficult to manage updates between (v8 itself makes this project entertaining on its own, no need to really complicate it).  I wouldn't begrudge anyone else wanting to start it, and would even help support it, but it's just a little more than I want to take on for a project that's 100% volunteer for me.  if you want to try, I have a pretty good list of the minimum requirements.

> That's weird. What do they hate about plv8?

I'm not even going to try to guess :)

**Comment by erichanson** [comment]
Yeah, what would it take to do a plv8u?

**Comment by JerrySievert** [comment]
funny you should ask, since [this](https://bellard.org/quickjs/quickjs.html) gets you quite far on that trek.  I was planning on taking a deeper look at it perhaps this weekend.

essentially, lots of `stdlib` wrappers, depending on how close to the node ecosystem one would want to get.  it ends up being a lot of boilerplate work going in and out of `v8`.

optimally, there'd be a full wrapper around `libpq`, and some deeper integration with pg internals that really aren't feasible in a trusted environment.

code wise:

* socket code (posix and windows) - c++
* file management (can live on socket code) - javascript
* native modules and management
* fully fleshed out module system
* `os`/`vm`/`process` compatibility with node
* a whole lot of testing and iteration

that's the shorter version of the list.

**Comment by pkit** [comment]
> I'm running into needing this again, this time trying to do some headless chrome / puppeteer stuff from plv8. Talk about a perfect screen-scraping and automation foundation, plv8 + puppeteer could be really incredible.
> 

Instead of going full untrusted (never go full untrusted inside the database) you can just drive puppeteer (or any other tool) through postgres notifications/messages. It's pretty easy to set-up a message listener (for example in nodejs) and then reroute these commands anywhere you like. In the end the only advantage you have with plv8 is fully synchronous transactions, but if you want to drive async tools anyway you don't have it in any case.
And it's pretty easy to support full Promise interface for these async notification tasks.
Just save the callback in the user context before firing notification and let the other side call stored procedure that deletes the reference from context and runs the callback when the task is finished.

**Comment by pkit** [comment]
Ok. I'm going to do it.
Essentially module support requires two big features:

1. FileSystem.
2. Import resolution.

Implementing FS is pretty easy, in fact I'm almost ready with it.
I ride on top of Postgres LOB support, which honors user permissions as of >=10 (I think even earlier, but didn't check)
I also use a modified `ltree` for fast traversals (which may be a problem because it's another dependency).

Implementing imports doesn't look too bad either, in fact d8 has a pretty good implementation which I'm gonna steal.
In the end d8 relies on 2 functions for resolution:

- GetWorkingDirectory()
- ReadFile()

I think a brain-dead approach will work here: hardcode cwd to `/` (it's only use is to search for entry point anyway) and use `plv8.resolve_module` akin to `plv8.start_proc` for absolute path (or bare specifier) to string (source code) resolution.

**Comment by JerrySievert** [comment]
wow, you're on a roll!  that would be an awesome addition.

**Comment by pkit** [comment]
@JerrySievert got some code today. But it's problematic.
Spec for ESM states that top level `await` and `async` dynamic load must be supported...
And I'm totally not in the mood of writing a microtask executor.
Will think about it.

**Comment by JerrySievert** [comment]
@pkit I feel you there.  that's part of the reason I hadn't pursued it.

**Comment by pkit** [comment]
@JerrySievert I suppose the following is a good API idea https://nodejs.org/api/esm.html#esm_experimental_loaders
But these are not final. Probably will postpone the `import` implementation till the loader spec matures.
Although I think I will still play around with the simpler cases: no async import, only static analysis.

**Comment by erichanson** [comment]
Glad to see this feature getting some love.  Thanks!

**Comment by pkit** [comment]
Wrote some more code and I fail to understand how it can be implemented in an embedded context at all.
I.e. when people created the `module` spec they did not think of any execution context other than the browser.
`plv8` is not a browser and will never be.
When script is run in a DBMS context it is used through an on-demand call interface, i.e. something outside of the database calls some entry point and then the script runs and returns some value (and/or changes some state).
In the case of modules there is no semantic for running a function. None. At all.
The only clear cut way to reference a module inside a function is `const mod = await import('mod')` which is just an ugly async version of `require()` that adds nothing but problems.
According to the spec modules are executed exactly once, and `plv8` functions are executed on each call, not gonna work here either.
And in the end using `rollup`/`webpack` to compile any newest ES syntax into `cjs` will work for years anyway...
