### ISSUE TITLE
Allow direct table/index access from plv8 without SQL

### ISSUE THREAD

**Issue by felixge** [plv8/plv8js#358]
As hinted in https://github.com/plv8/plv8/issues/356 I've had this idea in my head for a while that it could be really cool to directly access tables and indexes from plv8 without having to write SQL queries.

For example, this is how the equivalent of `SELECT * FROM foo WHERE id > 3` could look like:

```js
CREATE OR REPLACE FUNCTION example() RETURNS TABLE(
	id text,
	val text,
)
LANGUAGE plv8 STABLE AS
$$
  for (let row of plv8.seqscan('foo')) {
    if (row.id > 3) {
      plv8.return_next(row);
    }
  }
$$;
```

If your initial reaction is: "why on earth would you want to do this", then I totally understand. My desire for having such an API is mostly curiosity around a few things:

- Would it be possible to achieve better query plans than the query planner in some cases? (I'm pretty sure the answer here is yes, sometimes it's really hard to make PostgreSQL pick the most optimal plan despite being mindful of statistics, CTE fences, etc.)
- Would it be possible to have lower execution overheads in some cases? (I suspect the overheads of converting the tuples between C->JS->C is probably too high, but maybe not?)
- Would this make for a nice educational tool to show people what happens below the hood for some sample queries? (I think yes!)

I have a very lame PoC patch over here that implements a seqscan method that returns an array of rows: https://gist.github.com/felixge/65dd156c6d396ede35fb6f261658562f

Anyway, I'm certainly by no means advocating to use JS instead of SQL in most cases. That's why my code name for this project has been "excalibur" so far 🙈 

That being said, assuming I manage to write some decent patch for this, could you imagine merging such a feature into plv8?

If yes I'd like to try to implement a proper `seqscan()` and `indexscan()` (btree) method and send you a patch.

Cheers
Felix

**Comment by JerrySievert** [comment]
> If your initial reaction is: "why on earth would you want to do this", then I totally understand. My desire for having such an API is mostly curiosity around a few things:

actually, it's not - I've thought of the same thing myself, but let me add a couple of specific responses that might help you understand some of the scope and reasons why I've approached it very lightly:

> Would it be possible to achieve better query plans than the query planner in some cases? (I'm pretty sure the answer here is yes, sometimes it's really hard to make PostgreSQL pick the most optimal plan despite being mindful of statistics, CTE fences, etc.)

probably in some cases - pg's query planner is complicated, and parts of it have been the topic of discussion, you can follow those on pg-bugs and pg-hackers.  there are likely some cases where a more precise query plan can be written and followed, but depending on how deep you go, you might run into code that is actively being changed or refactored, so interfaces may end up getting changed since you wouldn't necessarily be dealing with public api's.

 > Would it be possible to have lower execution overheads in some cases? (I suspect the overheads of converting the tuples between C->JS->C is probably too high, but maybe not?)

I think I "proved" that when I opened a PR years ago against the node redis client that reimplemented the logic in javascript :)  same thing applies here - it's expensive to move between c++ and javascript, or "passing through the membrane" - I recall having a few discussions about it on the beach on Amelia island as well, when talking about how better to use leveldb.

it gets worse when dealing with pg's `Datum` system and converting that all the way through - you can look at `plv8_type.cc` where the jsonb direct conversion occurs to see those steps.  which is why I've toyed with the idea of "on-demand" conversion of jsonb, but haven't gone so far as to implement it yet.

but, here's where I take a step back:

plv8's a *trusted* language extension - it limits what you have access to by design.  chances are that an argument can be made that given the correct permissions checking and constraints that it can remain a trusted extension even while implementing something like this, but ...

as a language extension, plv8 already has "full access" to the database.  you can see some of the steps taken to ensure that a user doesn't have access to something they shouldn't just because the extension does:

https://github.com/plv8/plv8/blob/r3.0alpha/plv8_func.cc#L1070-L1127

1) I need to refactor all of this code into a single place, this case, and a couple of others have been patched over time and really need to be combined into a single cohesive check
2) it's changed with pg version changes where the underlying data structures have changed, and I expect it to change again
3) I'm assuming that rds/azure would not like something like this on by default because of possible risks, so it would likely need to be a compile-time flag

so, if it can overcome these hurdles, I'd definitely consider it.

**Comment by felixge** [comment]
@JerrySievert thanks for the detailed response! This makes perfect sense, and I agree that this shouldn't be enabled by default without high confidence that this doesn't negatively impact the security of the extension.

> but depending on how deep you go, you might run into code that is actively being changed or refactored, so interfaces may end up getting changed since you wouldn't necessarily be dealing with public api's.

The simplicity of the heap access API makes me hope that it wouldn't be difficult to keep up with changes, and maybe the new pluggable storage APIs will even help with making those interfaces more stable/public in the long run.

>  it's expensive to move between c++ and javascript, or "passing through the membrane" 

Yeah, that's what I remembered from my node days as well. But your idea of "on demand" conversion sounds very promising, so I think it might be possible to avoid a lot of those overheads depending on the use case.

> so, if it can overcome these hurdles, I'd definitely consider it.

Cool. Then I'll continue to hack on this and see how far I can get. I won't be heart-broken if you end up rejecting the patch, in the worst case I'll end up learning a lot :).

It'll probably be a while until I'm ready to submit a PR, so feel free to close this issue in the meanwhile if you want.

**Comment by JerrySievert** [comment]
I'm fine keeping the issue open in the mean time - it can facilitate discussion.

**Comment by pkit** [comment]
I would like to see such an interface. But I think securing it will be a pretty tough matter. Currently postgres has pretty tight and versatile security controls (RLS ftw!) implementing all of that will be challenging.

**Comment by felixge** [comment]
@pkit I haven't looked into the RLS implementation. Is it part of the executor? If yes it might be possible to piggy-back on the executors scan nodes for RLS support rather than accessing the heap directly.

**Comment by pkit** [comment]
@felixge did some research, RLS is applied at a query rewrite phase. I.e. it's a pretty high abstraction...

**Comment by felixge** [comment]
@pkit so you're saying it's going to be difficult to hook into that code, right?

**Comment by pkit** [comment]
@felixge it's a query rewrite phase, you will need to produce actual SQL query and then rewrite it using rls rewriter and only then you can invoke the executor. While now you're just hooking into low level execution functions.
I think that actually getting a sane in-isolate executor will be a huge thing (from security perspective), but pretty hard to get right.

**Comment by pkit** [comment]
P.S. you know what. I think plugging into FDW may be a faster way to get results.
Pity that there is no FDW implementation for V8/javascript right now...

**Comment by JerrySievert** [comment]
alternately, you can check the permissions on every table/index/schema, but that's going to be even more complicated and/or error prone.

pg security is tough to get right.

I will note that there's a thread on pg-hackers about how slow using SPI is, so there might be some gain to having an alternate path into the executor.

**Comment by pkit** [comment]
> I will note that there's a thread on pg-hackers about how slow using SPI is, so there might be some gain to having an alternate path into the executor.

I was actually amazed how fast it is :)
I was in a land of very low expectations, but in the real world if you compare to nodejs - it is fast enough. lol

**Comment by pkit** [comment]
> alternate path into the executor

Actually I need some sort of custom executor because otherwise it's nearly impossible to bill users on postgres usage. Even getting the disk space they used is a nightmare.

**Comment by JerrySievert** [comment]
PR's are often accepted :)

**Comment by pkit** [comment]
Yeah, I know, I'm trying to get there :)
Actually the first thing I'm trying is to plug into FDW.
But I'm not sure that it can be called `plv8` then, although plugging into the same isolate/context can be pretty beneficial.
