### ISSUE TITLE
Support for raw results from queries

### ISSUE THREAD

**Issue by mitar** [plv8/plv8js#365]
At least in [node-postgres](https://github.com/brianc/node-postgres), there is a significant performance difference if I access results from the query as raw payload (read: not decoded into objects or JavaScript values at all, but kept as what comes over the wire). The reason why this is useful sometimes is because in some cases I want just to proxy those results all the way to the client (browser) and then parse them. In this way there is no need to parsing in node and then serializing again to just parse in web browser again.

I do not know what happens in plv8 given that it runs inside the database, but if access to some form of raw buffer with data from the database is available, I think I would be interested in being able to access it directly, so that I could use NOTIFY to send it out as-is as well. So is this something which is available and then plv8 parses it before returning a JavaScript object?

**Comment by JerrySievert** [comment]
> So is this something which is available and then plv8 parses it before returning a JavaScript object?

you can access queries directly using SPI - this ends up being slower since plv8 is able to do direct conversion from types without needing to cross the c++/javascript membrane.

I know first hand that a pure javascript library like node-postgres can be much faster than using a c library, I was the one who did that for node-redis: moved it from using the c library to javascript directly.  but, this is an entirely different beast, it's not converting it into an intermediary to be converted into javascript.  if you're interested, I suggest looking at plv8_type.cc

you're talking about apples and bowling balls in this case.

**Comment by mitar** [comment]
> it's not converting it into an intermediary to be converted into javascript

Oh, based on [this comment](https://github.com/plv8/plv8/issues/224#issuecomment-309524659) I thought that "converting from postgres native types, to v8 native types, to javascript" still holds. This is why I got interested in trying to access "postgres native types" directly.

> plv8 is able to do direct conversion from types without needing to cross the c++/javascript membrane.

Oh, I wonder how is that possible. Let me look into `plv8_type.cc`, thanks.

**Comment by JerrySievert** [comment]
you were looking at a years-old comment.  if you're using a version of plv8 from either your operating system or from postgresql.org, you're using a many years out of date version.  plv8 has moved forward quite a bit since then.

**Comment by mitar** [comment]
No, I am using the latest, but I am trying to understand internals by reading through issues. :-) If there are more up to date things I could read, that would be awesome. I will also try to understand the code.

**Comment by JerrySievert** [comment]
> Oh, I wonder how is that possible.

because plv8 is written in c/c++ and operates directly on the `Datum` coming from the internals of postgres, not from a serialized or in any way cooked interface like node-postgres uses.  there's no faster way to get data from postgres itself.  the possible "improvements" are as follows:

1. direct access by going around the planner - because of security issues, will likely not ever occur because plv8 is a trusted extension, there's an issue open about it, go read if you're curious the implications
2. a direct object wrapper around jsonb types, but not convinced it will be any faster given how jsonb is stored and accessed, v8 is better at managing objects and arrays of javascript types, so while fun would likely impose a 5-10% performance penalty, but may lower brief memory usage (which occurs in another memory context and is freed immediately anyways)


and 3.0alpha is latest

**Comment by mitar** [comment]
Reading documentation [here](https://plv8.github.io/#database-access-via-spi), I do not see how I could get raw result. What I would probably want is access to `HeapTuple`s of `vals` field of `SPITupleTable` struct, as returned by the cursor. Is this what you mean with "`Datum` coming from the internals of postgres"? Why would accessing this go around the planner?

> direct access by going around the planner - because of security issues, will likely not ever occur because plv8 is a trusted extension, there's an issue open about it, go read if you're curious the implications

I think you mean https://github.com/plv8/plv8/issues/358? I am not asking for that. I would just like to simply directly access the buffer of returned data, without even any conversion which currently happens in `plv8_type.cc`, maybe just exposing it as an JavaScript `array` (if that can be done without copying). I would then send this directly to the client, and on the client I would then have code which would parse it (probably with many if statements based on which version of PostgreSQL the payload is coming from).

**Comment by JerrySievert** [comment]
> Reading documentation here, I do not see how I could get raw result. What I would probably want is access to HeapTuples of vals field of SPITupleTable struct, as returned by the cursor. Is this what you mean with "Datum coming from the internals of postgres"? Why would accessing this go around the planner?

three different things:

1. SPI is the interface that *you* have access to, plv8 itself has direct access to the underlying data
2. take a look at what `plv8.execute()` returns
3. I know you're not asking for what #358 wants, but since plv8 is *part of the database* it could have the ability to request the data directly without making a query, that's the level of integration that plv8 has, there's not client code sitting between it and the database, it *is* the database effectively.

> I would then send this directly to the client, and on the client I would then have code which would parse it

then you're missing a bit here - in the context of a plv8 stored procedure, there is no "client" and there cannot be.   plv8 cannot make a connection to the outside world, it can simply interface via database types.  if this means you want to coerce its internal types to a bitmap, you can, but plv8 cannot "return" or "pass" anything except as a database type.

if you're looking to expose postgres internals to node, plv8 will not do that for you - by design - it's a trusted extension, it cannot export or import data except through postgres types.

**Comment by mitar** [comment]
> take a look at what `plv8.execute()` returns

From documentation, it looks like it returns already parsed column values as objects.

"For SELECT queries, the returned value is an array of objects. Each object represents one row, with the object properties mapped as column names."

Am I missing something? Is there more than that returned?

> then you're missing a bit here - in the context of a plv8 stored procedure, there is no "client" and there cannot be

As mentioned in my initial post in this issue, I would be using `NOTIFY`. I think this should work from inside the plv8 stored procedure? So the question is, how can I get something from the database into `NOTIFY` with the least amount of copying/serialization/deserialization. `NOTIFY` accepts a string though, so maybe what I am hopping is not really possible.

**Comment by JerrySievert** [comment]
pretty easy to see the output of `plv8.execute()`:

```
[local] jerry@test=# do $$ plv8.elog(NOTICE, JSON.stringify(plv8.execute('SELECT * FROM test_table'))); $$ language plv8;
NOTICE:  00000: [{"name":"1","value":1},{"name":"2","value":2},{"name":"3","value":3},{"name":"4","value":4},{"name":"5","value":5},{"name":"6","value":6},{"name":"7","value":7},{"name":"8","value":8},{"name":"9","value":9},{"name":"10","value":10},{"name":"11","value":11},{"name":"12","value":12},{"name":"13","value":13},{"name":"14","value":14},{"name":"15","value":15},{"name":"16","value":16},{"name":"17","value":17},{"name":"18","value":18},{"name":"19","value":19},{"name":"20","value":20},{"name":"21","value":21},{"name":"22","value":22},{"name":"23","value":23},{"name":"24","value":24},{"name":"25","value":25},{"name":"26","value":26},{"name":"27","value":27},{"name":"28","value":28},{"name":"29","value":29},{"name":"30","value":30},{"name":"31","value":31},{"name":"32","value":32},{"name":"33","value":33},{"name":"34","value":34},{"name":"35","value":35},{"name":"36","value":36},{"name":"37","value":37},{"name":"38","value":38},{"name":"39","value":39},{"name":"40","value":40},{"name":"41","value":41},{"name":"42","value":42},{"name":"43","value":43},{"name":"44","value":44},{"name":"45","value":45},{"name":"46","value":46},{"name":"47","value":47},{"name":"48","value":48},{"name":"49","value":49},{"name":"50","value":50},{"name":"51","value":51},{"name":"52","value":52},{"name":"53","value":53},{"name":"54","value":54},{"name":"55","value":55},{"name":"56","value":56},{"name":"57","value":57},{"name":"58","value":58},{"name":"59","value":59},{"name":"60","value":60},{"name":"61","value":61},{"name":"62","value":62},{"name":"63","value":63},{"name":"64","value":64},{"name":"65","value":65},{"name":"66","value":66},{"name":"67","value":67},{"name":"68","value":68},{"name":"69","value":69},{"name":"70","value":70},{"name":"71","value":71},{"name":"72","value":72},{"name":"73","value":73},{"name":"74","value":74},{"name":"75","value":75},{"name":"76","value":76},{"name":"77","value":77},{"name":"78","value":78},{"name":"79","value":79},{"name":"80","value":80},{"name":"81","value":81},{"name":"82","value":82},{"name":"83","value":83},{"name":"84","value":84},{"name":"85","value":85},{"name":"86","value":86},{"name":"87","value":87},{"name":"88","value":88},{"name":"89","value":89},{"name":"90","value":90},{"name":"91","value":91},{"name":"92","value":92},{"name":"93","value":93},{"name":"94","value":94},{"name":"95","value":95},{"name":"96","value":96},{"name":"97","value":97},{"name":"98","value":98},{"name":"99","value":99},{"name":"100","value":100}]
```

if you want direct access to the `Datum`s that's not going to happen - at least in plv8.

as for `NOTIFY` there are much faster/easier ways than writing a stored procedure:

```
=# SELECT pg_notify('channel', name || value::VARCHAR) FROM test_table;
```

**Comment by mitar** [comment]
> pretty easy to see the output

Yes, and that is not raw output.

> if you want direct access to the Datums that's not going to happen - at least in plv8.

Why not? :-(

**Comment by JerrySievert** [comment]
> Why not? :-(

plv8 is a *trusted* extension.  it cannot provide raw access and still be a *trusted* extension.  if you want to create an extension that does that, go ahead, but you will be extremely limited in where you can run it.  it's a tradeoff: being able to use plv8 in RDS, or Azure, or any corporate data center, versus being able to use your home-grown extension on your own machine.

you might note that you don't typically see plpython or plperl available on hosting platforms.  there's a reason for that.

**Comment by mitar** [comment]
I think access to `Datum` does not break the trusted barrier? It is still what is returned from SPI, see [here](https://www.postgresql.org/docs/current/spi-spi-getvalue.html). So I agree we want to keep trusted extension, but I do not see how exposing whatever is given to `plv8_type.cc` as a binary array breaks anything? So I am just saying that I would like to access input to whole decoding process of `plv8_type.cc` directly, without it having to decode anything. Are you saying that input is sensitive?

**Comment by JerrySievert** [comment]
a postgres extension is analogous to a kernel module in linux - it's not running in user space, and has full access to everything in the database.  it's very simple to ignore all security checks in an extension and do whatever you want.  by design, plv8 is a *trusted* extension, meaning that it purposefully limits some access to what the database wants it to be able to access.

> I think access to Datum does not break the trusted barrier? 

being able to read/write memory to a point that you can crash the process does.  besides, a `Datum` format changes from postgres version to postgres version.

if you really want that level access, simple `CAST` to a buffer.  it will be slower, but will hand over the data to plv8 in a way that you seem to think will be faster.

**Comment by JerrySievert** [comment]
if you want to do something that will break for 99.9% of other users, then it's best to simply write your own extension.

**Comment by JerrySievert** [comment]
btw, here's some recommended reading for you:  https://www.postgresql.org/message-id/ed9da20e-01aa-d04b-d085-e6c16b14b9d7@postgrespro.ru

it should help you understand some of the challenges and work-arounds of dealing with SPI versus direct data manipulation.  still not something that will actively make it into plv8, but something to look at for writing your own custom extension.

**Comment by mitar** [comment]
> being able to read/write memory to a point that you can crash the process

So you are saying that the pointer the extension gets is not already a copy of data in the database, but a memory object which if it is written into could lead to security issues?

> a Datum format changes from postgres version to postgres version.

I am aware of that, but I am willing to handle that on the client side.

> if you really want that level access, simple CAST to a buffer.

`CAST` what to a buffer? The `Datum`?

But yes, casting Datum as binary into some read-only JavaScript array would be something I would like and I do not get why that would be a security problem?

I read the thread, but I do not see how exactly this relates to this discussion, except that plv8 seems to be the slowest. :-(

**Comment by JerrySievert** [comment]
> So you are saying that the pointer the extension gets is not already a copy of data in the database, but a memory object which if it is written into could lead to security issues?

if you go down that far, yes.  here's the documentation for the `Numeric` type: https://github.com/postgres/postgres/blob/master/src/backend/utils/adt/numeric.c#L135-L159

> I am aware of that, but I am willing to handle that on the client side.

that will be for you to deal with in the extension that you write.

> CAST what to a buffer? The Datum?

> But yes, casting Datum as binary into some read-only JavaScript array would be something I would like and I do not get why that would be a security problem?

that's not - that will give you an ArrayBuffer to work with, if you plan on trying to do something like this with plv8, using Postgres's supported functionality.

> I read the thread, but I do not see how exactly this relates to this discussion, except that plv8 seems to be the slowest.

yes, because crossing the c++/javascript membrane in v8 is slow - we both know that.  all I can do is give you pointers to documentation, this is not a "feature" that will be included in plv8.

**Comment by mitar** [comment]
Great. Thanks for all the responses. I really appreciate them.

**Comment by JerrySievert** [comment]
np, and I'm happy to give you any additional pointers, you're welcome to continue asking - I've been pretty deep in this stuff for years.

**Comment by JerrySievert** [comment]
though it might be best if you took it to email

**Comment by mitar** [comment]
Thanks for the offer. I will try first to investigate if this really brings any performance benefits before I go to deep into this. :-)

**Comment by JerrySievert** [comment]
I'm skeptical, just because the source of the values is coming from the c++ side of the membrane, not as text, so serialization isn't occurring but I'd love to hear how it works out.

**Comment by JerrySievert** [comment]
if you manage to find any specific gains that plv8 is missing, feel free to open a PR!
