### ISSUE TITLE
excessive memory consumed by set-return function 

### ISSUE THREAD

**Issue by tracyhenry** [plv8/plv8js#372]
Hi, 

I was running a set-returning function that returns about 2M `jsonb`. The returned records themselves do not consume much memory (about 200Mb). But when returning them, the consumed memory was up to 8G, regardless of the return method (array or plv8.return_next). 

Is this expected?

**Comment by JerrySievert** [comment]
it depends highly on which version of plv8 you are using, and how it is compiled.

if you are running 3.0, then it is unexpected.

if you are running 2.3.9 or older, then it is expected.

if you are running 2.3.10 or newer, it should be improved, and if you are running 2.3.10 or newer and have configured with `DIRECT_JSONB_CONVERSION=1` during the build process then it is unexpected.

**Comment by tracyhenry** [comment]
I'm running 2.3.11   Not sure if (200MB->8GB) is after improvement. 

I worked around this by doing batch inserts directly inside the function and not returning a set. So I don't plan to upgrade to 3 at this point. Feel free to close this.

**Comment by JerrySievert** [comment]
likely it is after the memory context improvements, but likely you do not have direct jsonb conversion enabled.

without the direct conversion, there end up being multiple copies of each jsonb object in memory due to the conversion method: `jsonb` -> `json` -> `v8 object`.

with direct jsonb conversion, essentially 2 of those go away.  you can enable it in 2.3.11 by building with `make DIRECT_JSONB_CONVERSION=1`.

since it is a major change, it was back ported into the 2.3 branch as a compile-time feature.
