### ISSUE TITLE
user context dies in pretty strange circumstances

### ISSUE THREAD

**Issue by pkit** [plv8/plv8js#393]
Yup. I see something like this in log:
```
2020-06-14 13:53:24.753 UTC [82/44290] 5ee49a79.52 ERROR:  missing error text
2020-06-14 13:53:24.753 UTC [82/44291] 5ee49a79.52 CONTEXT:
```
And the user context is dead on that connection: all the globals are deleted, `plv8_start` is not run, looks like a context was restarted(?) for some reason, but none of the bootstrap was run.
Not connected to any specific query or javascript function (although does happen much more frequently on frequenlty launched functions) and is overall pretty rare.
But still annoying because there is no "bad" condition that I can anchor it to.
Need to rely on heuristics: is the context really alive or not?
Needless to say: all other contexts on the same backend continue to function properly.
If there are any pointers on how to debug that one, will be appreciated.

**Comment by pkit** [comment]
Looks like `GetGlobalContext()` throws something...
But it's so hard to reproduce...

**Comment by JerrySievert** [comment]
hm.  if anyone could figure out how to reproduce in the wild, I'd guess it was you. :)

so I can think of better ways to debug, which version are you using in this case? 2.3 or 3.0?

**Comment by JerrySievert** [comment]
also knowing the pg version might help, trying to track down exactly where "missing error text" might come from.

**Comment by pkit** [comment]
I'm using the HEAD which is `r3.0alpha`
With PG 10.10
Did a workaround: created a stored proc to reset the user context properly `plv8_reset()` for now, if you want it in a PR, can do (I reset the context only if I see it's busted, much faster than reconnect, and doesn't interfere with the other contexts)
Do you have any pointers on why the error text can be missing?
Have another wild guess: all the functions that lead to the error use txid which is bigint as the last argument. May be a pure coincidence.

**Comment by JerrySievert** [comment]
first off, bear with me - slowly getting my context switched.  while I'm typically deep in c++ every day, it's been in DSP, not DB, so need to swap that portion of my brain back in :)

> if you want it in a PR, can do (I reset the context only if I see it's busted, much faster than reconnect, and doesn't interfere with the other contexts)

yeah, I'd definitely accept a PR for this - even when the issue is fixed, it will be nice to have the *option* of reseting the context.

> Do you have any pointers on why the error text can be missing?

that's what I'm unsure about, and why I asked about the pg version - I'll spend a few minutes trying to track down that portion of it.

> Have another wild guess: all the functions that lead to the error use txid which is bigint as the last argument

hm.  *if* that's the issue, then it is just as likely that an issue would be in plv8 as in this version of v8 (which is a scary proposition).  there are a couple of things to look at if that's the case.  3.0alpha handles BigInt conversion directly.

building with `BIGINT_GRACEFUL=1` would  enable the BigInt checks to drop down to a normal `Number`, which might help track down what's going on (if you can reproduce):

```
	case INT8OID: {
#if BIGINT_GRACEFUL
		int64 v = DatumGetInt64(datum);

		if (v > INT32_MAX || v < INT32_MIN)
			return BigInt::New(plv8_isolate, v);
		return Number::New(plv8_isolate, v);
#else
		return BigInt::New(plv8_isolate, DatumGetInt64(datum));
#endif
	}
```

but either way it converts to a `Int64Datum` on the way back out:

```
	case INT8OID:
		if (value->IsBigInt()) {
			BigInt *b = BigInt::Cast(*value);
			return Int64GetDatum((int64) b->Int64Value());
		}
		if (value->IsNumber())
			return Int64GetDatum((int64) value->IntegerValue(plv8_isolate->GetCurrentContext()).ToChecked());
		break;
```

the code is pretty simple and straightforward, and the only place where `INT8OID` is referenced.

need to take a walk to finish the mental context switch, then I'll see if I can track down where the missing error text could be coming from.

**Comment by JerrySievert** [comment]
well, at least I know where "missing error text" is coming from now:

```
src/backend/utils/error/elog.c
2882:		append_with_tabs(&buf, _("missing error text"));
3185:			err_sendstring(&msgbuf, _("missing error text"));
3293:			appendStringInfoString(&buf, _("missing error text"));
```

**Comment by JerrySievert** [comment]
the only place in code for plv8 that does not explicitly set an error message for `elog` is in `plv8_Elog`, which is the function called for `plv8.elog`.

otherwise, it would have to be a caught error that is passing through to:

```
/*
 * Write error report to server's log
 */
static void
send_message_to_server_log(ErrorData *edata)
```

my thoughts are that a `PG_TRY` could be failing and it is dropping through?

maybe drop an `elog` with a `DEBUG1` where `throw pg_error()` is being called in the `PG_CATCH` in `plv8_func.cc` and `plv8_type.cc`.  given your thought of it being a `txid`, it would likely be in `plv8_type.cc` (where there are only 7 of them).

**Comment by pkit** [comment]
Shit. It stopped reproducing.
The repro occurrence was approx 1:40,000 transactions...
Will need to monitor prod and install all that logging, thanks!

**Comment by pkit** [comment]
My hunch is that it fails somewhere here:
https://github.com/plv8/plv8/blob/r3.0alpha/plv8.cc#L1207-L1222

**Comment by pkit** [comment]
Nope, found it.
It's OOM error.
The thing is that we call `TerminateExecution()` when script is OOM.
But `TerminateExecution()` doesn't set any error message (found it in V8 test cases).
So we need to check in exceptions if we are in `IsTerminatingExecution()` state and set the error message accordingly "Out of memory" or something.
Will do another PR with that one.
And probably immediately resetting context after OOM is a pretty good option.
