### ISSUE TITLE
Does each change in function used as start_proc require a database restart?

### ISSUE THREAD

**Issue by cschwaderer** [plv8/plv8js#400]
I'm currently experimenting with `start_proc` and not 100% sure if I got it right. (Documentation is not really exhaustive here.)

First of all, my idea is preventing prototype pollution by freezing the prototype:

```
    Object.freeze(Object.prototype);
    Object.freeze(Object);
```

Do you think this is a sensible use-case for `start_proc`? Or will this cause unpredictable side-effects?

Now, more important: I have defined my `start_proc` in postgresql.conf and it seems to work.

Question is now: What do I have to do if there are changes in the function body of my `start_proc` function? Simply running `REPLACE FUNCTION` has no effect, obviously. However, is it really necessary to do a complete Postgres restart upon each change? That would be inconvenient on production. Or is there a way to just restart PLV8? Or am i missing something?

PostgreSQL version: 12.3
PLV8 version: 2.3.14

**Comment by JerrySievert** [comment]
> Do you think this is a sensible use-case for start_proc? Or will this cause unpredictable side-effects?

I think that it will cause unpredictable side-effects, but that could be just me :)

> However, is it really necessary to do a complete Postgres restart upon each change?

the `start_proc` exists for the lifetime of the v8 context.  a v8 context is per-role and is tied to the lifetime of the (forked) postgres backend that you are connected to.  by default, the postgres backed is destroyed when you disconnect and a new one is created upon next connection.

note that if you are running a connection pooler, this does not apply, as a connection pooler keeps connections open and recycles them.

you can see this in action yourself:

```
CREATE FUNCTION start() RETURNS VOID AS $$
  plv8.elog(NOTICE, "In start function");
$$ LANGUAGE plv8;
```

then disconnect (since checking the validity of the function requires a v8 context, which would have already run any start function).

on your new connection:

```
SET plv8.start_proc = 'start';
DO $$ plv8.elog(NOTICE, "Hello, World!") $$ LANGUAGE plv8;
```

you should see both messages.

you can then create another role:

```
CREATE ROLE foo;
```

and switch to it:

```
SET ROLE TO foo;
```

and execute again:

```
DO $$ plv8.elog(NOTICE, "Hello, World!") $$ LANGUAGE plv8;
```

you'll see another startup since the role has changed.

clean it up:

```
RESET ROLE;
DROP ROLE foo;
```

> Or is there a way to just restart PLV8?

until recently, no, since that's not how postgres is designed, but @pkit contributed some neat code in 3.0 recently that allows for the reset of the v8 context.  you can find the PR here: https://github.com/plv8/plv8/pull/395/files

note that this will not be back ported to the 2.x branches.
