### ISSUE TITLE
Cannot stop process if executing with plv8.execute

### ISSUE THREAD

**Issue by JamesInform** [plv8/plv8js#459]
Using: plv8 2.3.15

If I run the following statement
`do
$$
	plv8.execute("select pg_sleep(180)");
$$ language plv8;
`

I cannot stop the statement before the 180 seconds are over.

Wether 

`select pg_terminate_backend(pid) `

nor 

`select pg_cancel_backend(pid)`

is working.

What can I do?

**Comment by JerrySievert** [comment]
which operating system for the database, and which version of postgres?

**Comment by JamesInform** [comment]
I can reproduce it unter
Mac PG13, PG14
Ubuntu 20.04 PG13, PG14

**Comment by alessbelli** [comment]
Hi @JerrySievert - this was affecting our setup after we upgraded RDS versions, and this got down to a chase for the regression.
At this point this seems to work fine on any plv8 version until v2.3.3:
- you can either ctrl+c or pg_cancel_backend(pid) to kill long-running execution of inner SQL commands
- you can set a statement timeout that will get respected (#439)
- pure js infinite loops cannot be terminated  (issue #187)

(tested using [waldo2188/postgres-plv8](https://github.com/waldo2188/docker-postgres-plv8/blob/master/Dockerfile) on docker, which runs pg10 + plv8 2.3.3)

starting v2.3.4:
- pure js infinite loops seem to be terminatable with pg_cancel_backend / ctrl + c
- plv8 that runs long-running SQL commands can't get terminated
- plv8 execution doesn't respect statement timeouts.

(tested using [capitalch/xpostgres-plv8](https://github.com/capitalch/xpostgres-plv8/blob/master/Dockerfile) on docker, which runs pg10 + plv8 2.3.4 (the dockerfile doesn't match what's actually installed!)

The tests I ran were pretty simple:
- cancellability of inner SQL commands:
    - `DO $$ plv8.execute("SELECT pg_sleep(60)") $$ LANGUAGE plv8;`
- statement timeouts:
    - `BEGIN TRANSACTION; set local statement_timeout to 1000; DO $$ plv8.execute('select pg_sleep(2);') $$ LANGUAGE plv8; COMMIT;`
- infinite js loops
    - `DO $$ a = 1; while (true) {a+=1;}; $$ LANGUAGE plv8;`

I have very little knowledge of C, but it seems like this line / commit could be the culprit here https://github.com/plv8/plv8/commit/7ee42a929548d10e3d6c1a47a15db32b7a6e42f6#diff-446d05ea4a200a2528b9ca590124f25d2e64ca096b20a1e438c33b2b4300e1faR559

Apparently `signal` can only have one handler per signal, and returns the pointer to the previous one - this means that by setting up the new custom handler, the old one is never fired (which would align with the fact that the previous behavior was lost, and the infinite js loops were fixed.

This theory, however, doesn't quite track with my (very limited) knowledge of the code - because if I'm reading this correctly, calling the `signal` twice means that you would not end up calling the new custom handler (the first call registers the new handler, returns the old one, then the second call re-registers the old one, discarding the custom one).

Looking into this a bit deeper - with `set client_min_messages to 'debug';` I see that in v2.3.4, when you send cancel signal (ctrl+c) to the infinite loop that got fixed, there's now a proper "cancelling execution" elog.
_however_, when you send a cancel signal to the now broken long-running sql statement inside of plv8, this logs the message twice. Does this mean that there's an issue with the function pointer being used as the second handler? or is there an issue with propagating the signal across different contexts when the new handler is in place?

I hope this helps, and do let me know if there's anything more I can provide
Best,

**Comment by JerrySievert** [comment]
great find, and great work!  I'll try to track down the cause of the regression today.

**Comment by alessbelli** [comment]
> great find, and great work! I'll try to track down the cause of the regression today.

Thanks a lot! I'm not sure if I can be of any direct help, but do let me know if there's anything I can help with.

**Comment by alessbelli** [comment]
Hey @JerrySievert, I just wanted to know if you had gotten a chance to make progress on this one - I'd love to help if I can, and to get to a patch as soon as I can since our app relies pretty heavily on being able to cancel long-running queries for its stability.
Best,

**Comment by JerrySievert** [comment]
I worked on it some last week, and managed to get some interesting crashes instead of the desired behavior out of v8.

I am getting ready for travel at the moment, but hopefully will have some time again soon.

**Comment by JerrySievert** [comment]
3.1 has been released, this issue should be resolved.

**Comment by alessbelli** [comment]
> 3.1 has been released, this issue should be resolved.

Whoa huge news, thank you so much!

**Comment by alessbelli** [comment]
Hi again @JerrySievert - thanks again for your great work in fixing the signal propagation bugs.

I've been eager to try those out in the past few weeks, but maybe for lack of `Make` compilation experience, I haven't been able to ever get this to compile in some predictable environment from scratch (ubuntu, debian VMs, macOS) - I got various shapes of errors (recently the double free corruption error from #475) - and I wanted to know if you, or anyone else for that matter, was able to come up with a `Dockerfile`that builds the latest (3.1.2?) from scratch without errors.

For lack of that, the way that I've seen this lying around on dockerhub, is to have a precompiled binary as part of an image shared in there (which is much faster to spin up) but then again, I haven't seen anyone able to use the newer builds (The closest to "active" distributions that expose a full build command would be `ionx/postgres-plv8` (but it runs plv8 2.3) .
We'd like to submit the new fix into the pipeline for AWS RDS as part of their bi-monthly minor updates, but we want to test this out in isolated environments first.

Thanks again!

**Comment by alessbelli** [comment]
(I've been using github global searches on a regular basis to see if anyone would be able to compile and publish a dockerfile that worked for plv8 3.1+)
A few days ago, this https://github.com/sibedge-llc/plv8-dockerfiles was able to compile it, and I was therefore able to finally run the updated plv8 on an isolated environment.
Running the test cases seems to produce somewhat weird behavior, and I'm not sure whether to attribute that to improper compilation steps or to a bug in the plv8 patch that you added.
Essentially, no SQL query seems cancellable anymore, by itself or inside a stored procedure. (test cases 1 and 2, but pg_sleep in bare SQL too!)
The only thing that's cancellable in this install seems to be the infinite plv8 loop (test case 3).

In addition to this, a small extra observation seems to be that after trying (and failing) to cancel a statement, the following query always throws an error without a message ("missing error text" and empty context).

Does that sound plausible, and have you  run into any of this?

Thank you again for your support!

**Comment by hellower** [comment]
same.

```
SQL> \dx
                                              List of installed extensions
     Name     | Version |   Schema   |                                    Description
--------------+---------+------------+-----------------------------------------------------------------------------------
......
 plv8         | 3.1.1   | pg_catalog | PL/JavaScript (v8) trusted procedural language
....
(14 rows)

test@[local]:9081:test(19:37:28)
SQL> show statement_timeout ;
 statement_timeout
-------------------
 1min
(1 row)

Time: 0.474 ms
test@[local]:9081:test(19:37:41)
SQL> set statement_timeout='2s';
SET
Time: 0.340 ms
test@[local]:9081:test(19:37:56)
SQL> show statement_timeout ;
 statement_timeout
-------------------
 2s
(1 row)

Time: 0.323 ms
test@[local]:9081:test(19:37:57)
SQL>  DO $$ plv8.execute('select pg_sleep(10);') $$ LANGUAGE plv8;
DO
Time: 10399.402 ms (00:10.399)                       ------------------ statement_timeout not work
test@[local]:9081:test(19:38:13)
SQL>  DO $$ plv8.execute('select pg_sleep(10);') $$ LANGUAGE plv8;
ERROR:  missing error text                 --------------------------------------------- ?????
CONTEXT:
Time: 1.067 ms
test@[local]:9081:test(19:38:16)
SQL>  DO $$ plv8.execute('select pg_sleep(10);') $$ LANGUAGE plv8;
DO
Time: 10027.666 ms (00:10.028)
test@[local]:9081:test(19:38:27)
SQL>  DO $$ plv8.execute('select pg_sleep(10);') $$ LANGUAGE plv8;
ERROR:  missing error text
CONTEXT:
Time: 1.131 ms
test@[local]:9081:test(19:38:30)
SQL>
```

**Comment by alessbelli** [comment]
Hi again @JerrySievert, do you have any updates on this? as far as testing went it still seems broken on the latest release.

**Comment by sfingram** [comment]
I've created PR #493 that addresses the cancellation issue.  With the proposed change, it will now cancel in both the JS case and the SQL case.

But there is still a subsequent error with the termination interrupt that is manifested in the behavior in [one of the previous comments.](https://github.com/plv8/plv8/issues/459#issuecomment-1108966691).  This error happens when the cancellation occurs while executing SQL.  As far as I can tell here is the sequence:

1.  postgres cancels sending a SIGINT to the process which is currently executing `SPI_exec` in `plv8_Execute`
2. `signal_handler` executes
3. it calls`running_context->isolate->TerminateExecution();` 
4. which than calls `isolate->stack_guard()->RequestTerminateExecution()` 
5. this raises an interrupt (see the interrupt list `INTERRUPT_LIST` in `stack_guard.h`),  setting the `_interrupt_flags_` of the isolate's `StackGuard`

So now the isolate's `StackGuard` has an interrupt triggered, but, because we've finished execution, it hasn't triggered an termination exception.

The next time we execute `plv8` code in postgres, it will execute the method `CompileFunction`, where there is a call to the following block of code
```javascript
	if (Script::Compile(isolate->GetCurrentContext(), source, &origin).ToLocal(&script)) {
		if (!script.IsEmpty()) {
			if (!script->Run(isolate->GetCurrentContext()).ToLocal(&result)) {
				if (isolate->IsExecutionTerminating()) {
					isolate->CancelTerminateExecution();
				} else {
					throw js_error(try_catch);
				}
			}
		}
	}
```
It is the call to `script->Run` that will actually raise the exception.  

I don't know enough about V8 to detect and clear the interrupt, but if there is a way to do that, it would resolve the problem. 
 I'm thinking something like the way it currently checks for termination
```javascript
	if (isolate->IsExecutionTerminating()) {
		isolate->CancelTerminateExecution();
	}
```
But the above methods only deal with exceptions, which have not been thrown yet.  It would need the analogue, but for interrupts.
