### ISSUE TITLE
Using pre-compiled build libraries

### ISSUE THREAD

**Issue by hmarzooq** [plv8/plv8js#470]
Hello!

Building plv8 extension roughly takes an hour. Therefore, I'm looking for a method where we can (re)use pre-compiled build libraries - perhaps by copy-paste of the required files (binaries). Please advise if its possible and what is the correct approach, provided all hosts are of same OS/Arcgiecture.

Thanks!

**Comment by JerrySievert** [comment]
depends on how you're referring to it.

if you're thinking of using v8 as a library (.so), then there's a high chance that won't work - the v8 team goes out of their way to make it a bad option, and it mostly results in a crash.

if you're thinking of storing binaries somewhere, and downloading them like brew, that's a pretty big project that I don't have the time or the budget to handle.

if you're thinking of the build system being smarter and not forcing recompiles, I have part of that rewritten as part of 3.1 but haven't had the time to make any more changes yet, so that should improve when 3.1 is released.

if you're talking about something else, tell me, and I can try to figure it out.

**Comment by hmarzooq** [comment]
> if you're talking about something else, tell me, and I can try to figure it out.

I was thinking what if, I copy "build" folder from a successful plv8 build & install form machine "A" to another machine "B" and run "make install", while assuming "make install" will get the required binaries from the copied "build" folder and will copy that during install at the appropriate locations on machine "B".

OR 

Find out where the "make install" on machine "A" has copied the files (*.so, *.bc,*.sql, etc) and do the same copy on machine B.

Note: Machine "A" and "B" has same OS/Architecture and file directory structure.

**Comment by hmarzooq** [comment]
Any thoughts ?

**Comment by hmarzooq** [comment]
Just to update, I tried what I suggested above and it does created the plv8 successfully.
