### ISSUE TITLE
When we run the "make static" command for Plv8 installation using ansible-playbook.The Process takes too much time

### ISSUE THREAD

**Issue by resulraveendran** [plv8/plv8js#476]
When we run the "make static" command for Plv8 installation using ansible-playbook.The Process takes too much time and it didn't complete.Plv8 version is r3.1 and the Postgres version is 13. We are not able to finish this task, Kindly help with this.

**Comment by resulraveendran** [comment]
ubuntu@ip-172-31-30-213:/tmp/plv8$ sudo make static 
make -f Makefiles/Makefile.linux v8
make[1]: Entering directory '/tmp/plv8'
Setting up build directory
Downloading LLVM
Downloading gn source
Building gn
cd build/gn && export PATH=$PATH:/tmp/plv8/build/clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-20.04/bin && python3 build/gen.py && ninja -C out/ gn
ninja: Entering directory `out/'
[194/194] LINK gn
Downloading v8 source
Patching v8
error: can't open patch '../../patches/*.patch': No such file or directory
Downloading up third party sources

**Comment by ghost** [comment]
plv8 configuration is using more size to download, suspecting need to wait till to complete.

I have run this on my Laptop for 2 hr., then killed process and having 7GB+.

**Comment by JerrySievert** [comment]
unfortunately, in order to build plv8, v8 must also be built.  it is a requirement of v8 to be built from source, pinned, and embedded.

also, as v8 is updated (and 3.1 required a v8 update), it ads complexity and compile time.  there is nothing that the plv8 project can do to get around this other than drop v8.

closing.
