### ISSUE TITLE
PostgreSQL 15 build error (plv8 v2.3.15)

### ISSUE THREAD

**Issue by JamesInform** [plv8/plv8js#496]
Hi Jerry,

are there any plans to update v2 for PostgreSQL 15 compatibility?!

I cannot switch to V3 because of Bigint handling.

Cheers,
James

**Comment by JerrySievert** [comment]
hi @JamesInform which part of BigInt handling are you having issues with?

**Comment by JamesInform** [comment]
Hi @JerrySievert 

My existing scripts are not considering Bitint, but Bigint is produced when accessing INT8 columns. And it's a huge effort to rewrite them all. Well, if you don't plan to update V2, I will have to :)

Btw.: Should the plv8 / Master compile against PG15? I am getting errors like "cannot find nija".

**Comment by JerrySievert** [comment]
I asked because there is an additional compilation option that is not on by default:

https://github.com/plv8/plv8/blob/r3.1/Makefile#L77

this attempts a conversion to 32bit if it can and falls back to a real `BigInt` if it cannot.  it might be a way for you not to have to convert immediately.

you should be using the `r3.1` branch, or a tagged release.  if it is complaining about `ninja`, then you need to follow the build guidelines, as they changed as of 3.1.

I have not compiled against the 15 beta yet, but it likely will work as the pg team has been making a lot less breaking changes in the last few releases.  I haven't had a change to try yet, but I am releasing a new 3.1 release soon and will make sure it builds before I do.

**Comment by JerrySievert** [comment]
indeed it looks like a few things break for compiling c++ in pg15 - I will get the 3.1 version up to date before I initiate another release.

**Comment by JamesInform** [comment]
That's great!

Thanks!

**Comment by JerrySievert** [comment]
I've released 3.1.4, which should now work well with the pg15 beta.

**Comment by JamesInform** [comment]
Now it successfully compiles against PG15B3!!!

Concerning the BIGINT_GRACEFUL:

> I asked because there is an additional compilation option that is not on by default:
> 
> https://github.com/plv8/plv8/blob/r3.1/Makefile#L77
> 
> this attempts a conversion to 32bit if it can and falls back to a real BigInt if it cannot. it might be a way for you not to have > to convert immediately.

How do I set the additonal compilation option?
How do I call the make command and pass BIGINT_GRACEFUL to be defined?

`make BIGINT_GRACEFUL=1`
doesn't work.

Can you give an example?

**Comment by JamesInform** [comment]
Now I see that all went fine.

Is there a chance that BIGINT_GRACEFUL handles int8 like float like in PLV8 v2?

**Comment by JerrySievert** [comment]
`BIGINT_GRACEFUL` attempts to coerce into a standard `Number` if the number that Postgres provides is within the range of a 32 bit number, otherwise it converts to a `BigInt` instead.  converting to a float loses resolution, which is an incorrect implementation now that `BigInt` exists.  the `BIGINT_GRACEFUL` flag attempts to make it easier for porting to `BigInt` without breaking _everything_ for the developer.

https://github.com/plv8/plv8/blob/r3.1/plv8_type.cc#L947-L955 shows the actual difference.

**Comment by JamesInform** [comment]
Well currently it's

![image](https://user-images.githubusercontent.com/38714600/185964667-fec5b391-3e70-4ea7-9980-6928691e4853.png)

What about
`if (v > 9007199254740992 || v < -9007199254740992)`

That would represent the max and min value that JavaScript can handle as an integer.
[Integer max/min](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Number)

Do you think I'll run into issues, if I set those values just for my own compilation?

**Comment by JerrySievert** [comment]
I mean, I wouldn't exactly recommend it, but you're welcome to try.  remember that even `BIGINT_GRACEFUL` is essentially an unsupported configuration.

but, if it saves you from updating for `BigInt` in the short term, it might be a viable solution for you.
