### ISSUE TITLE
plv8 Performance with `SET ROLE`

### ISSUE THREAD

**Issue by ScottPierce** [plv8/plv8js#512]
I'm in the process of considering using plv8 with something called [postgraphile](https://www.graphile.org/postgraphile/introduction/). 

The documentation points out:

> In PLV8, each session has one global JS runtime context. This enables function invocations at low cost, and sharing common object among the functions. However, for the security reasons, if the user switches to another with SET ROLE command, a new JS runtime context is initialized and used separately. This prevents the risk of unexpected information leaking.

Postgraphile uses ROLES and RLS to get security out of accessing the database from the client side via a graphql api. I'm fairly certain that every postgraphile call uses `SET ROLE`. If we were to use this with plv8, `SET ROLE` would happen **before** the function call using plv8. I would probably be using this with

1. Would runtime contexts be cached between postgres roles? Each request would alternate between 3 roles - an admin, authenticator, and visitor.
2. We'd like a common library to be accessible from all of our functions. How would we allow this library to be accessible across every database role?
3. Do you have any recommendations for how we can get performance?

**Comment by JerrySievert** [comment]
hi, great questions.  I'll try to answer what I can, but chances are you're going to have more questions after I answer.

1. there is a cache created via Postgres's `hash_create` that creates a hash of initially 32 (arbitrarily chosen, but seems to work well) proc caches that are tied to a user id: https://github.com/plv8/plv8/blob/r3.1/plv8.cc#L350 - so, as long as the roles are within the same backend process, there should be very little context switch penalty except for the first switch into each role.
2. you can include any shared state or shared code via a startup procedure: https://plv8.github.io/#start-up-procedure - note that each context will get a copy of this, but any changes are not shared between contexts.  you can set this via a GUC which would occur at the database level (RDS, or whoever your provider is should give you access to this, as well as locally for any development).  in addition, if you're going to be making repeated calls to the same function, it might be useful to use `plv8.find_function()`: https://plv8.github.io/#-code-plv8-find_function-code-
3. thousands.  but a lot of it begins at the basics:

* use a bouncer to keep sessions open
* keep your data passing to a minimum, type conversions between postgres and v8 can be costly - much better in the 3.x releases than 2.x, at least for JSON/JSONB
* use as new of a version of plv8 as your provider offers, plv8 versions are tied to v8 versions, as new features were released of v8, those features are not backported due to incompatibilities - plus as noted, plv8 conversion code has improved over time
* put any shared functions into the plv8 namespace in your start procedure, once compiled it will be faster to run after the startup penalty

if you have any specific performance questions, I'm happy to answer, or any followup questions.

**Comment by ScottPierce** [comment]
Thank you for your response!

> as long as the roles are within the same backend process

I'm not following very well. Backend process is a server process connecting to the database? Or did you mean database process, in which case, isn't there only a single database process? Or are you speaking of a backend process as a single postgres connection?

> there should be very little context switch penalty except for the first switch into each role.
So I will only have to pay for the first switch?

> proc caches that are tied to a user id

Do you mean a postgres user / role? When you say `proc cache` what do you mean? 
As long as I connect to the database from the same connection string, it shouldn't be an issue, right?

> creates a hash of initially 32 (arbitrarily chosen, but seems to work well) proc caches

So is a proc cache used for each active function, or each active role being used? i.e. can I only have 32 active functions, or can I only have 32 roles that I switch between?

**Here is a scenario:**
So I have a horizontally scaling server with 2 instances, that are both connected to the database using the same connection string. If I run requests that switch to a single alternative user, I will only have to pay that price to switch to that user once, right?

**Comment by JerrySievert** [comment]
>> as long as the roles are within the same backend process

> I'm not following very well. Backend process is a server process connecting to the database? Or did you mean database process, in which case, isn't there only a single database process? Or are you speaking of a backend process as a single postgres connection?

postgres forks on every connection - which is why connection costs are so expensive and why it is usually suggested that you use a bouncer or connection pooler in front of it: each open connection stays active with the forked copy of postgres (I found a random page on duckduckgo that might help explain better: https://scalegrid.io/blog/postgresql-connection-pooling-part-1-pros-and-cons/)

once you disconnect from postgres, it destroys that backend, and creates another on a new connection.  as long as you don't close that connection, any state in that backend is kept.

so, typically, the architecture between your app and postgres looks like the following:

```mermaid
graph TD;
  Application1-->Pooler
  Application2-->Pooler
  Pooler-->Database1
  Pooler-->Database2
```
 _(edited to add a second application server in the diagram)_

and your pooler keeps the connection open to the forked backend.  when you connect from your application, you're not guaranteed the same connection or postgres backend.

assuming you have all of that in place, you should be a-ok.

> So is a proc cache used for each active function, or each active role being used? i.e. can I only have 32 active functions, or can I only have 32 roles that I switch between?

no, the hash grows, just noting that these are cached in the running backend, so switching between them is fairly trivial.

> So I have a horizontally scaling server with 2 instances, that are both connected to the database using the same connection string. If I run requests that switch to a single alternative user, I will only have to pay that price to switch to that user once, right?

depends entirely on the connection model as noted above.  assuming that postgres is set up sanely, with a pooler in front of it, and you don't reap those connections very often, then yes.  but, that's entirely a postgres thing - once you're connected, plv8 tries its best to keep everything ready for you: v8 startup isn't cheap either, so the more times you can reuse the same database backend, the better.

**Comment by ScottPierce** [comment]
Thank you for your detailed writeup and prompt responses.

I knew postgres had a new process per connection, I guess I just didn't put that pooling is so important for postgres. 

1. So without a connection pool, using plv8 is a bad idea anyways. 
2. If I were to use plpgsql for everything, having a connection pool would still yield massive performance improvements, so no matter what I do, plv8 or not, I need to invest in a connection pooling solution, which means it's not a complexity cost I should associate with using plv8, but rather postgres. Right?
3. Per connection, I should only have to pay the role switching price once. Am I understanding that correctly?

I was planning on use Google Cloud SQL, and using unix sockets to connect to the database via servers on Google Cloud Run. Looks like I need a better plan.

**Comment by ScottPierce** [comment]
4. I'm slightly worried that in the event of a database failure, and it fails over to it's HA counterpart, that all of a sudden it will have to spend a large amount of time creating v8 contexts  and installing the libraries in each new function call. Is this a valid concern? 
5. How much additional memory does plv8 use on my postgres db if it's creating an instance of v8 in each process? I assume each context would use hundreds of MB, especially if it's maintaining a JIT cache.

**Comment by JerrySievert** [comment]
> So without a connection pool, using plv8 is a bad idea anyways.

I'd say using postgres in general without a connection pool is a bad idea, regardless of any extensions.  I just want to be very clear that v8 has a startup penalty, which you can demonstrate for yourself:

```
psql (14.6 (Debian 14.6-1.pgdg110+1))
Type "help" for help.

postgres=# \timing
Timing is on.
postgres=# do $$ plv8.elog(NOTICE, 'hello'); $$ language plv8;
NOTICE:  hello
DO
Time: 96.211 ms
postgres=# do $$ plv8.elog(NOTICE, 'hello'); $$ language plv8;
NOTICE:  hello
DO
Time: 0.756 ms
postgres=# set role migrator;
SET
Time: 0.375 ms
postgres=> do $$ plv8.elog(NOTICE, 'hello'); $$ language plv8;
NOTICE:  hello
DO
Time: 44.887 ms
postgres=> do $$ plv8.elog(NOTICE, 'hello'); $$ language plv8;
NOTICE:  hello
DO
Time: 0.921 ms
```

in my case, first run is a 90ms, additional runs on the same backend less than 1ms.  after the `SET ROLE`, the context is created (lighter than a full v8 creation and initialization), and then subsequent executions are under 1ms.  when I switch back to the primary role (not shown), then I am still under 1ms per execution.

> If I were to use plpgsql for everything, having a connection pool would still yield massive performance improvements, so no matter what I do, plv8 or not, I need to invest in a connection pooling solution, which means it's not a complexity cost I should associate with using plv8, but rather postgres. Right?

correct.  I went into the explanation since it sounded like you either a) didn't have a connection pooler, or b) were removed enough from the architecture that it wasn't something you were considering.  but, it's a postgres best practice, that does have an affect on plv8's performance (as well as almost any other extension).

> Per connection, I should only have to pay the role switching price once. Am I understanding that correctly?

correct, once per role.  you can use the example above to verify and to get more precise timings.

> I was planning on use Google Cloud SQL, and using unix sockets to connect to the database via servers on Google Cloud Run. Looks like I need a better plan.

unfortunately, google cloud sql is completely opaque to me - you will want to check with what features they offer, and how they manage connections.  I know that like RDS/Aurora, it is not a vanilla postgres instance, but beyond that I do not know their underlying architecture.

> I'm slightly worried that in the event of a database failure, and it fails over to it's HA counterpart, that all of a sudden it will have to spend a large amount of time creating v8 contexts and installing the libraries in each new function call. Is this a valid concern?

the startup will likely be negligible compared to the database getting all of the data into memory.  but you can do the math via the example.

> How much additional memory does plv8 use on my postgres db if it's creating all these additional contexts?

depends on how much memory is getting allocated in the startup proc, otherwise they're pretty lightweight.

**Comment by ScottPierce** [comment]
I'm over-thinking this. Connection pooling is something that happens naturally with any good postgres connection library (as long as it's configured). Each server can be responsible for pooling its own connections. I don't need to create an additional server that sits between my servers and the database that pools connections. As my servers scale up and down, they will create new connections and be responsible for pooling their own connections.

Two final questions:
1. Is there anything you could point me at regarding installing libraries so that all my code for `plv8` so that all my js code can access them? If I'm understanding this correctly now, I will have to send the library somehow with every new connection so that the database is installed / accessible on the connection.
2. plpgsql does not incur this startup / setup cost, right? This startup / setup cost is specific to external languages, right?

**Comment by JerrySievert** [comment]
> Connection pooling is something that happens naturally with any good postgres connection library (as long as it's configured).

I will note that you will usually still be better off with a pooler in between for a myriad of reasons, but I'm not going argue the point with you. :)

> Is there anything you could point me at regarding installing libraries so that all my code for plv8 so that all my js code can access them? If I'm understanding this correctly now, I will have to send the library somehow with every new connection so that the database is installed / accessible on the connection.

https://plv8.github.io/#plv8ify

or I wrote something about 6 years ago that might work for you: https://github.com/JerrySievert/plv8-modules

> plpgsql does not incur this startup / setup cost, right? This startup / setup cost is specific to external languages, right?

I haven't dug very deep into the pl/pgsql interpreter to figure out its costs, but it is an interpreter, so there are some costs involved, yes, but I do not have numbers for you.  your best bet for that would be to write a sample function in each language, and figure out what makes the most sense for you with some criteria:

* cost of execution when warm
* cost of execution when cold
* estimation of how often it would be cold
* ecosystem pains
* language familiarity

that calculation is going to be different for every project, and will need to be understood as far as maintenance and maintainability goes.  every solution is going to have costs and tradeoffs, and I can help you understand what they will be with plv8, but for direct comparisons with other solutions it will vary so much that I'm afraid you'll just have to benchmark and do a cost/benefit analysis with your own data.

**Comment by ScottPierce** [comment]
**Thank you for this very detailed conversation. You've gone far beyond what a stranger is normally willing to, especially as a someone who also maintains a library. You've given me a significantly better three dimensional framework for which I now understand postgres, extenions, how how they are loaded and maintained in memory.**

**Comment by ScottPierce** [comment]
@JerrySievert why did you never continue work on https://github.com/JerrySievert/plv8-modules ?

**Comment by JerrySievert** [comment]
it seemed to solve the problem at the time, plus some of the ecosystem became so complicated and intermingled that it became harder to support some of the edge cases.  PR's welcome!
