### ISSUE TITLE
Quick question: plv8 and row level security

### ISSUE THREAD

**Issue by paulzakin** [plv8/plv8js#513]
Quick question! 

I see that plv8 is a trusted procedural language - I assume that extends to privileges assigned to each ROLE in PostgreSQL - but does that trust extend to row level security? It seems from  #512 that it does?

In other words, if a trigger is ultimately invoked on a Postgres connection/session with the ROLE set to USER, the trigger would only have the same permissions that the USER would have?

Just wanted to sanity check my understanding!

**Comment by JerrySievert** [comment]
plv8 functions run under the role specified by postgres.  what this means:

* if a role doesn't have access to a column, the stored procedure/function can't access it since it is running as that role
* v8 contexts are created for each role, so anything that role executes is isolated to its own context

> In other words, if a trigger is ultimately invoked on a Postgres connection/session with the ROLE set to USER, the trigger would only have the same permissions that the USER would have?

that depends - postgres has `security definer` and `security invoker` - whatever privileges that postgres assigns the stored procedure/function are inherited, so if the user is `user1` and the function is set to `security definer` and created by `user2` then the function will execute as the role `user2` as per Postgres's security and role definitions.

to be more succinct, plv8 gets passed a `role` from postgres and only has access to whatever that `role` has, but also isolates the function to that `role`.

**Comment by paulzakin** [comment]
Awesome, super helpful, thank you!
